convert -size 32x32 canvas:red res/drawable/play_black.png
convert -size 32x32 canvas:red res/drawable/home_white.png
convert -size 32x32 canvas:red res/drawable/play_white.png
convert -size 32x32 canvas:red res/drawable/menu_white.png
convert -size 16x16 canvas:red res/drawable/music_small.png
convert -size 32x32 canvas:red res/drawable/minus_black.png
convert -size 32x32 canvas:red res/drawable/pause_black.png
convert -size 32x32 canvas:red res/drawable/minus_white.png
convert -size 32x32 canvas:red res/drawable/page_down_white.png
convert -size 32x32 canvas:red res/drawable/home_black.png
convert -size 32x32 canvas:red res/drawable/plus_white.png
convert -size 32x32 canvas:red res/drawable/stop_white.png
convert -size 32x32 canvas:red res/drawable/volume_mute_white.png
convert -size 32x32 canvas:red res/drawable/search_black.png
convert -size 16x16 canvas:red res/drawable/listen_small.png
convert -size 32x32 canvas:red res/drawable/prev_white.png
convert -size 16x16 canvas:red res/drawable/folder_small.png
convert -size 32x32 canvas:red res/drawable/volume_white.png
convert -size 32x32 canvas:red res/drawable/next_black.png
convert -size 32x32 canvas:red res/drawable/power_black.png
convert -size 32x32 canvas:red res/drawable/plus_black.png
convert -size 32x32 canvas:red res/drawable/page_up_black.png
convert -size 16x16 canvas:red res/drawable/cursor_small.png
convert -size 32x32 canvas:red res/drawable/stop_black.png
convert -size 32x32 canvas:red res/drawable/power_white.png
convert -size 32x32 canvas:red res/drawable/page_up_white.png
convert -size 32x32 canvas:red res/drawable/icon_small.png
convert -size 32x32 canvas:red res/drawable/menu_black.png
convert -size 32x32 canvas:red res/drawable/next_white.png
convert -size 32x32 canvas:red res/drawable/search_white.png
convert -size 32x32 canvas:red res/drawable/prev_black.png
convert -size 32x32 canvas:red res/drawable/volume_black.png
convert -size 32x32 canvas:red res/drawable/pause_white.png
convert -size 32x32 canvas:red res/drawable/arrow_left_black.png
convert -size 32x32 canvas:red res/drawable/page_down_black.png
convert -size 32x32 canvas:red res/drawable/volume_mute_black.png
convert -size 32x32 canvas:red res/drawable/arrow_left_white.png
convert -size 64x64 canvas:red res/drawable-xhdpi/ic_action_like_red.png
convert -size 64x64 canvas:red res/drawable-xhdpi/ic_action_star_10.png
convert -size 64x64 canvas:red res/drawable-xhdpi/ic_action_star_0.png
convert -size 48x48 canvas:red res/drawable-hdpi/ic_action_like_red.png
convert -size 48x48 canvas:red res/drawable-hdpi/ic_action_star_10.png
convert -size 48x48 canvas:red res/drawable-hdpi/ic_action_star_0.png
convert -size 32x32 canvas:red res/drawable-mdpi/ic_action_like_red.png
convert -size 32x32 canvas:red res/drawable-mdpi/ic_action_star_10.png
convert -size 32x32 canvas:red res/drawable-mdpi/ic_action_star_0.png
