# https://github.com/softprops/action-gh-release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up JDK 1.8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          STORE_FILE: ../key.jks
        run: echo "$KEY_JKS" | base64 -d > key.jks; ./gradlew build; rm key.jks
      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk avr-remote-${{ github.ref_name }}.apk
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref,'rc') }}
          files: avr-remote-${{ github.ref_name }}.apk